general:
  package_name: foobar
  name: FooBar
  version: 0.1
  architecture: all
  maintainer:
    name: Anybody J.
    email: anybody@company.com
  authors:
    - {name: Somebody Wrote It, email: somebody@company.com}
  short_description: Gives a Bar to a Foo
  long_description: |
    This package consists of a set of functions of type foobar, blaaah.
     
    Long descriptions are cool.
  priority: optional
  section: utils
menu:
    command: foobar
    icon: files/foobar.png
    can_open_multiple_files: false
    expects_uris: false
    requires_terminal: false
    section: Applications/Office
depends:
  - {name: bash}
files:
  - {src: files/foobar.sh, dst: /usr/bin/foobar}
  - {src: files/foobar.gif, dst: /usr/share/foobar/}
