.TH PKGCREATOR 1 "06/03/2011"
.SH NAME
pkgcreator-gtk \- front-end for pkgcreator.
.SH SYNOPSIS
.B pkgcreator-gtk <file>
.SH AVAILABILITY
Debian-based GNU/Linux distributions
.SH DESCRIPTION
.B pkgcreator-gtk
allows the editing of pkgcreator's YAML files, as well as a launcher for the application.
For further documentation and examples of pkgcreator's YAML files, refer to the project's website.
.SH FILES
A single input YAML file may be given as an argument.
.SH AUTHOR
.B pkgcreator-gtk
and its manual page were written by
Leandro Resende Mattioli <leandro.mattioli@gmail.com>
.SH "SEE ALSO"
pkgcreator Website: http://code.google.com/p/pkgcreator
